/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DashboardX7k2RouteImport } from './routes/dashboard-x7k2'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardX7k2QuickRouteImport } from './routes/dashboard-x7k2_.quick'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardX7k2Route = DashboardX7k2RouteImport.update({
  id: '/dashboard-x7k2',
  path: '/dashboard-x7k2',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardX7k2QuickRoute = DashboardX7k2QuickRouteImport.update({
  id: '/dashboard-x7k2_/quick',
  path: '/dashboard-x7k2/quick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard-x7k2': typeof DashboardX7k2Route
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/dashboard-x7k2/quick': typeof DashboardX7k2QuickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard-x7k2': typeof DashboardX7k2Route
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/dashboard-x7k2/quick': typeof DashboardX7k2QuickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard-x7k2': typeof DashboardX7k2Route
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/dashboard-x7k2_/quick': typeof DashboardX7k2QuickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard-x7k2'
    | '/gallery'
    | '/menu'
    | '/dashboard-x7k2/quick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard-x7k2'
    | '/gallery'
    | '/menu'
    | '/dashboard-x7k2/quick'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard-x7k2'
    | '/gallery'
    | '/menu'
    | '/dashboard-x7k2_/quick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardX7k2Route: typeof DashboardX7k2Route
  GalleryRoute: typeof GalleryRoute
  MenuRoute: typeof MenuRoute
  DashboardX7k2QuickRoute: typeof DashboardX7k2QuickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-x7k2': {
      id: '/dashboard-x7k2'
      path: '/dashboard-x7k2'
      fullPath: '/dashboard-x7k2'
      preLoaderRoute: typeof DashboardX7k2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-x7k2_/quick': {
      id: '/dashboard-x7k2_/quick'
      path: '/dashboard-x7k2/quick'
      fullPath: '/dashboard-x7k2/quick'
      preLoaderRoute: typeof DashboardX7k2QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardX7k2Route: DashboardX7k2Route,
  GalleryRoute: GalleryRoute,
  MenuRoute: MenuRoute,
  DashboardX7k2QuickRoute: DashboardX7k2QuickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
